# Inventory file - sử dụng SSM connection
all:
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_region: ap-southeast-1  # Đổi region theo thực tế
    ansible_aws_ssm_bucket_name: "ansible-ssm-sts-2026"  # Để trống nếu không cần S3 bucket cho file transfer

  children:
    monitoring_server:
      hosts:
        monitor-ec2:
          ansible_aws_ssm_instance_id: i-0a8e1d26b3f31cc0e

    target_servers:
      hosts:
        target-ec2-ts-oms:
          ansible_aws_ssm_instance_id: i-056d7d119373fd7c3
          private_ip: "20.10.11.56"          # ← Đổi thành IP thực tế
          install_phpfpm_exporter: true
        # Thêm target mới ở đây:
        # target-ec2-2:
        #   ansible_aws_ssm_instance_id: i-0abc123456789
        #   private_ip: "10.0.1.200"
        #   install_phpfpm_exporter: true