# Inventory file - sử dụng SSM connection
all:
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_region: ap-southeast-1  # Đổi region theo thực tế
    ansible_aws_ssm_bucket_name: "ansible-ssm-sts"  # Để trống nếu không cần S3 bucket cho file transfer

  children:
    monitoring_server:
      hosts:
        monitor-ec2:
          ansible_aws_ssm_instance_id: i-07f529f2770a5bfa5

    target_servers:
      hosts:
        target-ec2:
          ansible_aws_ssm_instance_id: i-03a7cd36465405052
          install_phpfpm_exporter: true
