# Inventory UAT environment
all:
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_region: ap-southeast-1
    ansible_aws_ssm_bucket_name: "ansible-ssm-sts-2026"

  children:
    monitoring_server:
      hosts:
        monitor-ec2:
          ansible_aws_ssm_instance_id: i-0a8e1d26b3f31cc0e

    target_servers:
      hosts:
        target-ec2-ts-oms:
          ansible_aws_ssm_instance_id: i-056d7d119373fd7c3
          private_ip: "20.10.11.56"
          install_phpfpm_exporter: false
        target-ec2-TS-M247-Prod:
          ansible_aws_ssm_instance_id: i-006f4edb282a8e84d
          private_ip: "20.10.2.121"
          install_phpfpm_exporter: true
        target-ec2-TS-M247-Prod-2:
          ansible_aws_ssm_instance_id: i-05d1e3c586f06a1d6
          private_ip: "20.10.2.243"
          install_phpfpm_exporter: true
        target-ec2-TS-Ecom-Gateway:
          ansible_aws_ssm_instance_id: i-01667b110e973054c
          private_ip: "20.10.2.125"
          cadvisor_version: "v0.49.1"
          cadvisor_extra_args: "--store_container_labels=true --housekeeping_interval=10s --allow_dynamic_housekeeping=true"
        target-ec2-TS-M247-Cron:
          ansible_aws_ssm_instance_id: i-0ae93a49a72bc8557
          private_ip: "20.10.2.35"
          install_magento_cron_monitor: true
          install_cadvisor: false
