---
phpfpm_exporter_version: "2.2.0"
phpfpm_exporter_port: 9253

# Đổi theo cấu hình php-fpm trên server:
# - Nếu php-fpm listen TCP: "tcp://127.0.0.1:9000/status"
# - Nếu php-fpm listen Unix socket: "unix:///var/run/php/php-fpm.sock;/status"
phpfpm_scrape_uri: "unix:///run/php/php8.3-fpm.sock;/status"

# Path tới pool config file
phpfpm_pool_config: "/etc/php/8.3/fpm/pool.d/www.conf"
